title: James Alvey
description: > # this means to ignore newlines until "baseurl:"
  I am currently studying for PhD in Theoretical Physics at King's College London.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: James Alvey # add your name
author-img: james-alvey.jpg # add your photo
about-author: I am a PhD student in Theoretical Particle Physics and Comsology at King's College London. I am interested in how to model the early Universe and use data from Cosmology to constrain new physics. <br/> <br/> My work so far covers Big Bang Nucleosynthesis, Graph Networks in the context of the Cosmic Microwave Background, the Direct Detection of Light Dark Matter, and Neutrino Astrophysics. # add description
social-twitter: James_A_42# add your Twitter handle
social-github: james-alvey-42 # add your Github handle
social-linkedin: james-alvey-a75845102 # add your Linkedin handle
social-email: AlveyJBG@gmail.com # add your Email address

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
